services:
  api:
    build: .
    container_name: transporte_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/transporte_db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
  
  db:
    image: postgres:15-alpine
    container_name: trasporte_db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=transporte_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d transporte_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
